# Generated by Django 5.0.1 on 2024-02-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='notif',
            field=models.BooleanField(default='False', verbose_name='Notifications'),
        ),
    ]
