# Generated by Django 5.0.1 on 2024-02-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_user_info_notif'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='vno',
            field=models.IntegerField(default='1', max_length=3),
        ),
        migrations.AddField(
            model_name='movies_hollywood',
            name='vno',
            field=models.IntegerField(default='3', max_length=3),
        ),
        migrations.AddField(
            model_name='movies_surprises',
            name='vno',
            field=models.IntegerField(default='4', max_length=3),
        ),
        migrations.AddField(
            model_name='movies_theatre',
            name='vno',
            field=models.IntegerField(default='2', max_length=3),
        ),
    ]
