# Generated by Django 5.0.1 on 2024-03-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_movies_vno_movies_hollywood_vno_movies_surprises_vno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=300)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AlterField(
            model_name='movies',
            name='vno',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='movies_hollywood',
            name='vno',
            field=models.IntegerField(default='3'),
        ),
        migrations.AlterField(
            model_name='movies_surprises',
            name='vno',
            field=models.IntegerField(default='4'),
        ),
        migrations.AlterField(
            model_name='movies_theatre',
            name='vno',
            field=models.IntegerField(default='2'),
        ),
    ]
