# Generated by Django 5.0.1 on 2024-03-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_user_review_alter_movies_vno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_review',
            name='rating',
            field=models.IntegerField(max_length=10),
        ),
    ]
