# Generated by Django 5.0.1 on 2024-03-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_user_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
