# Generated by Django 5.0.1 on 2024-03-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_user_review_slug_user_review_vno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_review',
            name='slug',
            field=models.IntegerField(default='0'),
        ),
    ]
