# Generated by Django 5.0.1 on 2024-03-22 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_user_review_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_review',
            new_name='user_reviews',
        ),
    ]
