# Generated by Django 5.0.1 on 2024-03-22 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_user_review_user_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_reviews',
            new_name='user_review',
        ),
    ]
