# Generated by Django 5.0.1 on 2024-06-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_user_reviews_user_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='notif',
        ),
    ]
