# Generated by Django 5.0.1 on 2024-06-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_user_info_notif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='email_address',
            new_name='email',
        ),
    ]
