# Generated by Django 5.0.1 on 2024-06-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_review',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=75),
        ),
    ]
